version: '2.24.6'
services:
  my-app:
    build: . 
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=secret
    ports:
      - 5000:5000

  mongodb:
    image: mongo:4.4.29-focal
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./db:/data/db
        
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
 